
package com.ooredoo.wsclient.spr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SDM_PROCESS_DATA_ptt", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/Application1/SDM_PROCESS_DATA/SDM_PROCESS_DATA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SDMPROCESSDATAPtt {


    /**
     * 
     * @param inputParameters
     * @return
     *     returns com.ooredoo.wsclient.spr.OutputParameters
     */
    @WebMethod(operationName = "SDM_PROCESS_DATA", action = "SDM_PROCESS_DATA")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/SDM_PROCESS_DATA", partName = "OutputParameters")
    public OutputParameters sdmPROCESSDATA(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/SDM_PROCESS_DATA", partName = "InputParameters")
        InputParameters inputParameters);

}
