
package com.ooredoo.wsclient.spr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SDM_PROCESS_DATA_ptt-bindingQSService", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/Application1/SDM_PROCESS_DATA/SDM_PROCESS_DATA", wsdlLocation = "http://10.192.206.45:6003/SDM_SB/ProxyServices/SDM_PROCESS_DATAProxy?wsdl")
public class SDMPROCESSDATAPttBindingQSService
    extends Service
{

    private final static URL SDMPROCESSDATAPTTBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SDMPROCESSDATAPTTBINDINGQSSERVICE_EXCEPTION;
    private final static QName SDMPROCESSDATAPTTBINDINGQSSERVICE_QNAME = new QName("http://xmlns.oracle.com/pcbpel/adapter/db/Application1/SDM_PROCESS_DATA/SDM_PROCESS_DATA", "SDM_PROCESS_DATA_ptt-bindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.192.206.45:6003/SDM_SB/ProxyServices/SDM_PROCESS_DATAProxy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SDMPROCESSDATAPTTBINDINGQSSERVICE_WSDL_LOCATION = url;
        SDMPROCESSDATAPTTBINDINGQSSERVICE_EXCEPTION = e;
    }

    public SDMPROCESSDATAPttBindingQSService() {
        super(__getWsdlLocation(), SDMPROCESSDATAPTTBINDINGQSSERVICE_QNAME);
    }

    public SDMPROCESSDATAPttBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SDMPROCESSDATAPTTBINDINGQSSERVICE_QNAME, features);
    }

    public SDMPROCESSDATAPttBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, SDMPROCESSDATAPTTBINDINGQSSERVICE_QNAME);
    }

    public SDMPROCESSDATAPttBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SDMPROCESSDATAPTTBINDINGQSSERVICE_QNAME, features);
    }

    public SDMPROCESSDATAPttBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SDMPROCESSDATAPttBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SDMPROCESSDATAPtt
     */
    @WebEndpoint(name = "SDM_PROCESS_DATA_ptt-bindingQSPort")
    public SDMPROCESSDATAPtt getSDMPROCESSDATAPttBindingQSPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/Application1/SDM_PROCESS_DATA/SDM_PROCESS_DATA", "SDM_PROCESS_DATA_ptt-bindingQSPort"), SDMPROCESSDATAPtt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SDMPROCESSDATAPtt
     */
    @WebEndpoint(name = "SDM_PROCESS_DATA_ptt-bindingQSPort")
    public SDMPROCESSDATAPtt getSDMPROCESSDATAPttBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/pcbpel/adapter/db/Application1/SDM_PROCESS_DATA/SDM_PROCESS_DATA", "SDM_PROCESS_DATA_ptt-bindingQSPort"), SDMPROCESSDATAPtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SDMPROCESSDATAPTTBINDINGQSSERVICE_EXCEPTION!= null) {
            throw SDMPROCESSDATAPTTBINDINGQSSERVICE_EXCEPTION;
        }
        return SDMPROCESSDATAPTTBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
